import jwt from 'jsonwebtoken';
import { env } from '../config/env.js';
import { HTTP_STATUS } from '../config/constants.js';

/**
 * JWT Authentication Middleware
 *
 * Validates Bearer tokens generated by the PHP legacy system.
 * On success, attaches the decoded payload to `req.user`.
 */
export function authMiddleware(req, res, next) {
  const authHeader = req.headers.authorization;

  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(HTTP_STATUS.UNAUTHORIZED).json({
      error: 'Missing or malformed Authorization header.',
    });
  }

  const token = authHeader.split(' ')[1];

  try {
    const decoded = jwt.verify(token, env.JWT_SECRET);
    req.user = decoded;
    return next();
  } catch (err) {
    const message =
      err.name === 'TokenExpiredError'
        ? 'Token expired.'
        : 'Invalid token.';

    return res.status(HTTP_STATUS.UNAUTHORIZED).json({ error: message });
  }
}
